openapi: 3.1.0
info:
  title: Unified Model Gateway API
  version: 0.1.0
  description: >
    Provider-agnostic API aggregation layer with unified request/response schema,
    routing, fallback, streaming (SSE), and async jobs.
servers:
  - url: https://api.example.com
security:
  - ApiKeyAuth: []
tags:
  - name: Responses
  - name: Jobs
  - name: Models
  - name: Usage

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'Use: Authorization: Bearer <api_key>'

  schemas:
    ErrorResponse:
      type: object
      required: [error]
      properties:
        error:
          type: object
          required: [code, message, request_id]
          properties:
            code:
              type: string
              description: Stable platform error code.
              examples: [AUTH_INVALID, RATE_LIMITED, PROVIDER_TIMEOUT, CAPABILITY_UNSUPPORTED]
            message:
              type: string
            request_id:
              type: string
              description: Server-generated request id for support.
            details:
              type: object
              additionalProperties: true
            provider:
              type: object
              properties:
                name: { type: string, examples: [openai, anthropic] }
                status_code: { type: integer, examples: [429, 500] }
                raw_code: { type: string }
                raw_message: { type: string }

    UnifiedMessage:
      type: object
      required: [role, content]
      properties:
        role:
          type: string
          enum: [system, user, assistant, tool]
        content:
          type: array
          description: Multi-part content, supporting text and media.
          items:
            oneOf:
              - $ref: '#/components/schemas/TextPart'
              - $ref: '#/components/schemas/ImagePart'
        name:
          type: string
          description: Optional speaker name (tool name when role=tool).
        tool_call_id:
          type: string
          description: Used when role=tool to bind tool result to a call.

    TextPart:
      type: object
      required: [type, text]
      properties:
        type: { type: string, const: text }
        text: { type: string }

    ImagePart:
      type: object
      required: [type, image_url]
      properties:
        type: { type: string, const: image_url }
        image_url:
          type: object
          required: [url]
          properties:
            url: { type: string, description: "HTTPS URL or signed URL." }

    ToolSpec:
      type: object
      required: [name, description, parameters]
      properties:
        name: { type: string }
        description: { type: string }
        parameters:
          type: object
          description: JSON Schema for tool input.

    ResponseFormat:
      type: object
      description: Request structured output.
      properties:
        type:
          type: string
          enum: [text, json_schema]
        json_schema:
          type: object
          description: JSON Schema when type=json_schema

    RoutingConstraints:
      type: object
      properties:
        budget:
          type: object
          properties:
            max_cost_usd: { type: number, minimum: 0 }
            max_latency_ms: { type: integer, minimum: 0 }
        routing:
          type: object
          properties:
            strategy:
              type: string
              enum: [cost, latency, reliability, quality]
              default: reliability
            allow_providers:
              type: array
              items: { type: string }
            deny_providers:
              type: array
              items: { type: string }
        region:
          type: object
          properties:
            data_residency:
              type: string
              description: "Logical region constraint."
              examples: [SG, US, EU]

    GenerationParams:
      type: object
      properties:
        max_output_tokens: { type: integer, minimum: 1 }
        temperature: { type: number, minimum: 0, maximum: 2 }
        top_p: { type: number, minimum: 0, maximum: 1 }
        seed: { type: integer }
        stop:
          type: array
          items: { type: string }
        response_format:
          $ref: '#/components/schemas/ResponseFormat'
        tools:
          type: array
          items: { $ref: '#/components/schemas/ToolSpec' }

    UnifiedRequest:
      type: object
      required: [model, input]
      properties:
        model:
          type: string
          description: "Public model name in catalog."
          examples: [gpt-4.1, claude-3.5-sonnet]
        input:
          type: object
          description: "Either messages or prompt; messages preferred."
          properties:
            messages:
              type: array
              items: { $ref: '#/components/schemas/UnifiedMessage' }
            prompt:
              type: string
        generation:
          $ref: '#/components/schemas/GenerationParams'
        constraints:
          $ref: '#/components/schemas/RoutingConstraints'
        stream:
          type: boolean
          default: false
        webhook_url:
          type: string
          description: "If present, request may be executed as async job."
        metadata:
          type: object
          additionalProperties: true

    Usage:
      type: object
      properties:
        input_tokens: { type: integer }
        output_tokens: { type: integer }
        total_tokens: { type: integer }
        cost_usd: { type: number }

    UnifiedOutput:
      type: object
      properties:
        type: { type: string, enum: [message, tool_call] }
        message:
          $ref: '#/components/schemas/UnifiedMessage'
        tool_call:
          type: object
          properties:
            id: { type: string }
            name: { type: string }
            arguments_json: { type: object, additionalProperties: true }

    UnifiedResponse:
      type: object
      required: [id, object, created, model, outputs]
      properties:
        id: { type: string }
        object: { type: string, const: response }
        created: { type: integer, description: "Unix epoch seconds" }
        model: { type: string }
        provider:
          type: object
          properties:
            name: { type: string }
            model: { type: string }
            region: { type: string }
        outputs:
          type: array
          items: { $ref: '#/components/schemas/UnifiedOutput' }
        usage:
          $ref: '#/components/schemas/Usage'
        request_id:
          type: string
        metadata:
          type: object
          additionalProperties: true

    SSEEvent:
      type: object
      required: [type, data]
      properties:
        type:
          type: string
          enum:
            - response.created
            - response.delta
            - response.usage
            - response.completed
            - response.failed
        data:
          type: object
          additionalProperties: true

    JobCreateRequest:
      type: object
      required: [request]
      properties:
        request:
          $ref: '#/components/schemas/UnifiedRequest'

    Job:
      type: object
      required: [id, status, created, request]
      properties:
        id: { type: string }
        status:
          type: string
          enum: [queued, running, succeeded, failed, canceled]
        created: { type: integer }
        updated: { type: integer }
        request:
          $ref: '#/components/schemas/UnifiedRequest'
        response:
          $ref: '#/components/schemas/UnifiedResponse'
        error:
          $ref: '#/components/schemas/ErrorResponse'

    ModelInfo:
      type: object
      required: [id, public_name, modality, capabilities]
      properties:
        id: { type: string }
        public_name: { type: string }
        modality: { type: string, enum: [text, image, video, audio, embedding] }
        capabilities:
          type: object
          additionalProperties: true
        pricing:
          type: object
          additionalProperties: true
        regions:
          type: array
          items: { type: string }

paths:
  /v1/responses:
    post:
      tags: [Responses]
      summary: Create a unified response (sync or stream).
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/UnifiedRequest' }
      responses:
        "200":
          description: Unified response (non-stream).
          content:
            application/json:
              schema: { $ref: '#/components/schemas/UnifiedResponse' }
        "202":
          description: Accepted as async job when webhook_url present or server decides.
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Job' }
        "400":
          description: Bad Request
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
        "401":
          description: Unauthorized
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
        "429":
          description: Rate limited
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }

  /v1/responses/stream:
    post:
      tags: [Responses]
      summary: Create a unified response with SSE streaming.
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/UnifiedRequest' }
      responses:
        "200":
          description: SSE stream of unified events.
          content:
            text/event-stream:
              schema:
                type: string
                description: SSE events where each 'data:' is a JSON-encoded SSEEvent.

  /v1/jobs:
    post:
      tags: [Jobs]
      summary: Submit an async job explicitly.
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/JobCreateRequest' }
      responses:
        "202":
          description: Job created.
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Job' }
        "400":
          description: Bad Request
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
    get:
      tags: [Jobs]
      summary: List jobs (basic pagination can be added later).
      responses:
        "200":
          description: Job list.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items: { $ref: '#/components/schemas/Job' }

  /v1/jobs/{id}:
    get:
      tags: [Jobs]
      summary: Get job by id.
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Job detail.
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Job' }
        "404":
          description: Not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }

  /v1/models:
    get:
      tags: [Models]
      summary: List available public models with capabilities.
      responses:
        "200":
          description: Model list.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items: { $ref: '#/components/schemas/ModelInfo' }

  /v1/usage:
    get:
      tags: [Usage]
      summary: Get aggregated usage (tenant/project scope via auth).
      parameters:
        - in: query
          name: from
          schema: { type: string, format: date-time }
        - in: query
          name: to
          schema: { type: string, format: date-time }
      responses:
        "200":
          description: Usage rollup.
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_cost_usd: { type: number }
                  total_tokens: { type: integer }
                  by_model:
                    type: array
                    items:
                      type: object
                      properties:
                        model: { type: string }
                        cost_usd: { type: number }
                        tokens: { type: integer }
